name: movie_viewer
description: Movie Viewer example
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc:               ^6.1.0
  flutter_bloc:       ^6.0.6
  dio:                ^3.0.9
  get_it:             ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:       ^1.0.0
  json_serializable:  ^3.2.0
  mockito:            ^4.1.3

flutter:
  uses-material-design: true